### ISSUE TITLE
Notifications are not sent to contributors

### ISSUE THREAD

**Issue by iamkingsleyf** [Automattic/Edit-Flow#651] opened 2021-05-20 13:46 UTC
Hi,

Notifications are not sent to contributors when their post is live, instead, a **NO ACCESS** https://imgur.com/PiS70ZD badge is displayed beside their names.

Our SMTP is working fine THANK YOU, we are able to get comments notifications, password reset, admins get notified when articles are submitted but once they are published or deleted they don't get emails.

**Comment by htdat** [comment] 2021-05-21 04:56
Hi @iamkingsleyf, 

> Notifications are not sent to contributors when their post is live, instead, a NO ACCESS https://imgur.com/PiS70ZD badge is displayed beside their names. 

This is the expected behavior. If users have `NO ACCESS` to a specific post, they will not be notified. 

Relevant PR https://github.com/Automattic/Edit-Flow/pull/492
Code: 

http://github.com/Automattic/Edit-Flow/blob/124c3cde900c22abe15c04b0b2bd11e306b2aef4/modules/notifications/notifications.php#L384-L388

**Comment by iamkingsleyf** [comment] 2021-05-21 05:38
Even if that user submitted the article? When the user submits the article admin (site email) is notified but when the admin publish the post it becomes NO ACCESS and the user doesn't get notified even when the said article is deleted.

**Comment by htdat** [comment] 2021-05-22 02:56
@iamkingsleyf It sounds like an interesting case. 
Would you mind doing the following steps? 

1. Try testing again this issue with only Edit Flow and a monitoring email plugin such as https://wordpress.org/plugins/wp-mail-logging/? Does the issue persist? 
2. If the issue persists, could you give us the exact steps to replicate the behavior you mentioned above?

**Comment by htdat** [comment] 2021-05-31 02:31
@iamkingsleyf I am closing this issue here. But if you need any updates, feel free to comment here or open a new issue. Thank you!

**Comment by iamkingsleyf** [comment] 2021-05-31 05:39
The issue still exists, i don't know if i am the only one having this issue out of 10k active install or many people have no idea what's going on

**Comment by htdat** [comment] 2021-05-31 06:32
@iamkingsleyf Thank you for the follow-up. 

I am trying to replicate this issue but I am not able to do that. Could you please give me detailed steps to reproduce it? 
Also as mentioned above, does this issue happen with only Edit Flow active? 

I am going to try replicating this issue again and will update here then.

**Comment by iamkingsleyf** [comment] 2021-05-31 06:39
yes, happens with only editflow active

**Comment by htdat** [comment] 2021-05-31 07:28
OK, I was finally able to replicate this issue. 

- Set up a WP site with only Edit Flow and https://wordpress.org/plugins/wp-mail-logging/
- Create a contributor account. 
- Use this contributor account to create a post for reviewing.
- An admin reviews this post, and adds this contributor to the notification list. 
- Try adding a comment in the `Editorial Comments` section. 
- This contributor still gets this comment via email (This can be checked through WP Mail Logging plugin).
- The admin publishes the post. 
- **The contributor does NOT get any email regarding this post published. => This is the issue here.** 

**However, this is actually _not_ a bug with Edit Flow. Instead, it's more how WordPress core handles capabilities for `Contributor` role by default.** As you see here https://wordpress.org/support/article/roles-and-capabilities/#contributor, contributors can `edit_posts` but they can not `edit_published_posts`.This explains why contributors no longer access their own posts after these posts are published by admins. And that also explains the current behavior of feature `Notifications` in Edit Flow. 

That said, a workaround is to give role `contributors` on your site this `edit_published_posts` capability. I tested this with https://wordpress.org/plugins/user-role-editor/ and confirmed it's working properly like what you want. **A note here is to please consider the implication of giving this capability to your contributors as it now allows your contributors to update their posts after their posts are published.**

**Comment by iamkingsleyf** [comment] 2021-05-31 09:56
But publishpress works?
user role is a big plugin you know.

**Comment by htdat** [comment] 2021-06-02 10:14
> But publishpress works?

It looks like that PublishPress is not implementing `user_can_be_notified` method as I do not find this method on [their code](https://github.com/publishpress/PublishPress/search?q=user_can_be_notified). 

> user role is a big plugin you know.
That's the easiest way to achieve what you want. Otherwise, you can write your own snippet to just add `edit_published_posts` for the `contributor` role on your site. 

That said, I notice that there is a useful filter [`ef_notification_user_can_be_notified`](http://github.com/Automattic/Edit-Flow/blob/1770298dcadc09ca29729e102c4584a7b41149b4/modules/notifications/notifications.php#L935-L935) that you can use to modify this behavior for contributors. 

I've written down this snippet and it works quite OK: 

```php
/**
 * Allow contributors get notifications after their posts are published
 *
 * @see https://github.com/Automattic/Edit-Flow/issues/651#issuecomment-851265959
 */
add_filter( 'ef_notification_user_can_be_notified', function ( $can_be_notified, $user, $post_id ) {
	if ( $user instanceof WP_User && in_array( 'contributor', $user->roles ) && $user->ID === (int) get_post_field( 'post_author', $post_id )) {
		return true;
	}
	return $can_be_notified;
}, 10, 3 );
```

**Comment by iamkingsleyf** [comment] 2021-06-02 15:10
Thanks, publishpress was a folk of edit flow though.
I will add the code to my function.php file.

**Comment by iamkingsleyf** [comment] 2021-06-02 16:12
Did not work, only 1 email was sent and that is to the admin.
https://imgur.com/YS7W6ti the code was added to the theme function.php

**Comment by htdat** [comment] 2021-06-03 02:28
> Thanks, publishpress was a folk of edit flow though.

Thanks for pointing this out. I am aware of this. Since PublishPress forked Edit Flow, that's possible that they do not sync their fork back with what has been changed in Edit Flow. In other words, most of the features are quite similar between Edit Flow and PublishPress. But going into details, there are subtle differences like what we're discussing here. 

> I will add the code to my function.php file.
> Did not work, only 1 email was sent and that is to the admin.

I've tried adding this code to the functions.php of my active theme on my site. I confirm the same issue happens like you mentioned here. This can happen sometimes and that depends on the order of loading hooks as well as if a specific request loads this functions.php file. 

Instead, you might want to change the place you're loading this snippet on your site: 

1. (Easiest) Use this plugin https://wordpress.org/plugins/code-snippets/ (I tested this and it works!)
2. Create a mu-plugin file and add the snippet above. For example, in my testing site, I am adding this snippet in this file: wp-content/mu-plugins/edit-flow-contributors.php

**Comment by iamkingsleyf** [comment] 2021-06-03 05:42
**(Easiest) Use this plugin https://wordpress.org/plugins/code-snippets/ (I tested this and it works!)**

You did not state where the code will run, but I have choose admin area

**Comment by htdat** [comment] 2021-06-03 09:17
> You did not state where the code will run, but I have choose admin area

I just left with the default option: `Run snippet everywhere`. 
I hope that the code is working for you.

**Comment by iamkingsleyf** [comment] 2021-06-03 10:07
Did you use any SMTP plugin? 
We use zohomail and I don't see it get sent to the author

**Comment by iamkingsleyf** [comment] 2021-06-03 10:54
i think its working partially, will keep and eye on it

**Comment by htdat** [comment] 2021-06-08 02:15
> Did you use any SMTP plugin?

@iamkingsleyf  - I am not using any STMP plugin as it's my test site. Instead, I am using this plugin to log all emails sent from WordPress: 

- https://wordpress.org/plugins/wp-mail-logging/

You may use it to test this feature too. Otherwise, Edit Flow has nothing to do with STMP. 

> i think its working partially, will keep and eye on it

How is it now? I hope that's it's working for you correctly.

**Comment by iamkingsleyf** [comment] 2021-06-08 06:12
Seems to be working on one site
thank you

**Comment by htdat** [comment] 2021-06-08 08:29
Thank you for your update as well as co-operation so far. I am very confident that it's working correctly. In case, you still have any issues, feel free to let us know. 
I am going to close this issue again.

**Closed by htdat** 2021-06-08 08:29 UTC

**Comment by iamkingsleyf** [comment] 2021-06-08 08:31
when are we expecting an update?

**Comment by htdat** [comment] 2021-06-08 09:23
As I explained the in the comment above https://github.com/Automattic/Edit-Flow/issues/651#issuecomment-851265959, this is not considered a bug. Therefore we're not going to address it. 

Instead, with the current code, there is a filter allowing us to change the way this behavior and you can customize it like what you want https://github.com/Automattic/Edit-Flow/issues/651#issuecomment-852903449.
