### ISSUE TITLE
Updating failed.

### ISSUE THREAD

**Issue by iamkingsleyf** [Automattic/Edit-Flow#625] opened 2020-12-09 19:24 UTC
Hi,

When in the EDITOR SCREEN if we CLICK save as PENDING or DRAFT we are greeted with an error message **Updating failed.**
Checking our log we found the below error. We are using guternbug and wordpress 5.6

`[Wed Dec 09 19:14:40.474555 2020] [proxy_fcgi:error] [pid 31420] [client 197.210.85.230:39274] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined function get_sample_permalink() in /home/498746.cloudwaysapps.com/domain-name/public_html/wp-content/plugins/edit-flow/modules/custom-status/custom-status.php:1555\nStack trace:\n#0 /home/498746.cloudwaysapps.com/domain-name/public_html/wp-includes/class-wp-hook.php(287): EF_Custom_Status->fix_get_sample_permalink()\n#1 /home/498746.cloudwaysapps.com/domain-name/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters()\n#2 /home/498746.cloudwaysapps.com/domain-name/public_html/wp-content/plugins/link-whisper-premium/core/Wpil/Model/Post.php(519): apply_filters()\n#3 /home/498746.cloudwaysapps.com/domain-name/public_html/wp-content/plugins/link-whisper-premium/core/Wpil/Model/Post.php(97): Wpil_Model_Post->get_sample_permalink()\n#4 /home/498746.cloudwaysapps.com/domain-name/public_html/wp-content/plugins/link-whisper-premium/core/Wpil/Model/Post.php(58): Wpil_Model_Post->getViewLink()\n#5 /home/498746.cloudwaysapps.com/domain-name/public_h...', referer: https://thexplorion.com/wp-admin/post.php?post=111933&action=edit`

**Comment by htdat** [comment] 2021-04-12 04:16
@iamkingsleyf - I've tested this issue with the plain WordPress 5.7, and Edit-Flow. I do not see any issue like this. 

That said, looking at your error log, I am seeing another plugin too:

```
#2 /home/498746.cloudwaysapps.com/domain-name/public_html/wp-content/plugins/link-whisper-premium/core/Wpil/Model/Post.php(519)
``` 
This may be a compatibility issue with this plugin `link-whisper-premium`. 

- What's about if you do not use this plugin, and use only Edit Flow? Do you have the same issue?
- If disabling Edit Flow, does the issue persist? 

Two questions above help narrow down the cause of this issue.

**Comment by iamkingsleyf** [comment] 2021-04-12 06:47
The problem has been fix the MAJOR problem with EDITFLOW is it does not send notification to contributors. We use a vultr server on cloudways and zohomail SMTP

**Comment by htdat** [comment] 2021-04-12 09:16
> The problem has been fix 

Glad to hear that. I am closing this GH issue here. 

> the MAJOR problem with EDITFLOW is it does not send notification to contributors. 
> We use a vultr server on cloudways and zohomail SMTP

Would you mind creating a new issue and outline all steps to replicate the issue? We recommend checking the reset-password feature in your WordPress site, and ensure SMTP work.

**Closed by htdat** 2021-04-12 09:16 UTC
Labels: [Status] Needs Reporter Feedback
