### ISSUE TITLE
Calendar throws notices

### ISSUE THREAD

**Issue by barryceelen** [Automattic/Edit-Flow#524] opened 2019-10-24 00:29 UTC
When loading the calendar view in the admin:

```
PHP Notice:  Trying to get property 'labels' of non-object in /var/www/html/wp-content/mu-plugins/edit-flow/modules/calendar/calendar.php on line 1597
PHP Notice:  Trying to get property 'singular_name' of non-object in /var/www/html/wp-content/mu-plugins/edit-flow/modules/calendar/calendar.php on line 1597
```

**Comment by mjangda** [comment] 2019-10-31 02:54
Hi @barryceelen! Thanks for the report.

Which version of Edit Flow are you using? Also, are you using any custom post types? If so, can you share how those are registered?

**Comment by mjangda** [comment] 2019-10-31 17:45
I've tested several variations of registering a custom type with missing labels or data, for example:

```
function book_setup_post_type() {
  $args = array(
    'public'    => true,
  );
  register_post_type( 'book', $args );
}
add_action( 'init', 'book_setup_post_type' );
```

But cannot reproduce. I'm going to close this but if you can share reproduction steps, happy to take another look.

**Closed by mjangda** 2019-10-31 17:45 UTC
