### ISSUE TITLE
New post has no status

### ISSUE THREAD

**Issue by RoccoMarco** [Automattic/Edit-Flow#394] opened 2017-04-27 15:42 UTC
Creating new post I was expecting that status will be the one I have chosen as default.

The status is empty. Taking a look to database it is saved as autodraft.

Is this a bug?

**Comment by RoccoMarco** [comment] 2017-04-27 16:35
Looking at database the problem is that autosave saves the post as auto-draft or draft. I have solved this using this filter

/**
 * @brief     Fires on post insert forcing default state according to edit flow.
 * @param[in] array $postdata    the post data as a keyed array.
 *
 * @return    array the modified post data.
 */
function pe_post_save($postdata) {
  if((strcmp($postdata['post_status'], 'draft') == 0) ||
     (strcmp($postdata['post_status'], 'autodraft') == 0)) {
    global $edit_flow;
    if(is_a($edit_flow, 'edit_flow')) {
      $status = $edit_flow->custom_status->get_default_custom_status()->slug;
      $postdata['post_status'] = $status;      
    }
  }
  return $postdata;
}
add_action( 'wp_insert_post_data', 'pe_post_save');

**Comment by justnorris** [comment] 2018-01-18 09:29
Hi @RoccoMarco,
WordPress is automatically saving drafts for you even when you don't save your posts. I think that instead of making WordPress turn them instantly into "Pitches" (or whichever default status you've given your edit flow) - drafts should be simply hidden from calendar. 

That way, while someone is working on a draft - it won't appear on the calendar, and when they click "Save Post" it'll have it's default status and show up. 

Would that make sense?

**Comment by dchymko** [comment] 2019-10-31 20:25
Sounds like this may not be a bug, as auto-saves are working as intended here.  Will close this issue out for now, but feel free to re-open if there is additional context.

**Closed by dchymko** 2019-10-31 20:25 UTC
Labels: [Priority] Medium, [Status] Needs Confirmation, [Status] Needs Reporter Feedback, bug
