### ISSUE TITLE
When a post type has custom status admin search don't work

### ISSUE THREAD

**Issue by spathon** [Automattic/Edit-Flow#274] opened 2014-08-15 13:58 UTC
This applies to search all statuses (default view). WordPress will create a SQL query with post_status=all instead of post_status IN (publish, draft etc).

**Comment by cojennin** [comment] 2016-04-28 23:39
Hrm, not sure I understand the issue. Is it that the admin search isn't searching the correct posts, or when Edit Flow is enabled the admin search doesn't return any posts?

When searching for posts from the admin on WP 4.5 with Edit Flow 0.8.1 the search is working as I expect. 

1. If I have a post with the title "Test Post" and I search for "test post", I see "Test Post" in the results.
2. If I have a post with the title "Test Post" and I search for "tost pest", no results are returned.

**Comment by spathon** [comment] 2016-04-29 05:34
It was that if you had Edit Flow and had created a custom *post_status* (e.g. other than draft, publish etc) then the search in admin didn't return any posts in a search. 
Some where in the code WordPress creates the SQL and converts all/any to the SQL `posts_status IN (publish, draft, etc)` but with Edit Flow AND had created a custom post_status in Edit Flow this was not happening and generated this SQL `post_status = 'all'`and no posts has post_status=all.
The code in my previous comment removed any SQL to limit by post_status.

The site must have been in WP late 3.x or 4.0 and no idea what version of Edit Flow. 
I don't have access to the site and don't work with WordPress anymore so I can't tell if new versions of WP or ED have fixed the issue.
Good luck

**Comment by cojennin** [comment] 2016-04-29 11:36
Gotcha. Thanks for checking back in on this issue! 

Tried the following steps and was still unable to reproduce using WP 4.5 and Edit Flow 0.8.1:

1. Created a new custom status called "New Status"
2. Created a new post called "Test Post" with the status "New Status"
3. Searched in the admin for "test post" and it was correctly returned
4. Searched in the admin for "tost pest" and did not get any results (as expected)

Going to close this issue out since I'm unable to reproduce it. If anyone else notices it I'll open a new ticket on it and make sure to reference this one. Thanks!

**Closed by cojennin** 2016-04-29 11:36 UTC
