### ISSUE TITLE
Calendar has duplicate days: November 2nd occurs twice, scheduled posts appear for both days

### ISSUE THREAD

**Issue by ieatbugs** [Automattic/Edit-Flow#286] opened 2014-10-28 01:12 UTC
The date of November 2nd occurs twice on the calendar - posts that are scheduled for this day display on both instances of November 2nd in the calendar.

**Comment by cojennin** [comment] 2016-04-28 23:21
I am also not able to reproduce the issue. Do you have more details?

**Comment by cojennin** [comment] 2016-05-17 19:05
Not able to reproduce and have not had any further feedback, suggesting close.

**Comment by cojennin** [comment] 2016-09-02 14:48
Closing. Feel free to reopen or create a new ticket if you encounter this issue again and can provide more information!

**Closed by cojennin** 2016-09-02 14:48 UTC
Labels: close
