### ISSUE TITLE
Bug with WP 5.2.2

### ISSUE THREAD

**Issue by beceha** [Automattic/Edit-Flow#510] opened 2019-06-20 09:58 UTC
With WP 5.2.2 and EDITFLOW active you cannot switch between visual and text tab editor, and you cannot scroll within the editor window, when there is a lot of text in it. 

This does not happen with current EDITFLOW version and WP 5.2.1.

**Comment by mikeyarce** [comment] 2019-08-19 21:33
Thanks for the bug report, @studioart !

> With WP 5.2.2 and EDITFLOW active you cannot switch between visual and text tab editor, and you cannot scroll within the editor window, when there is a lot of text in it.

What version of Edit-Flow are you using?  I tried this with the latest `master` and WordPress 5.2.2 and I don't see any issues:

![edit-flow1](https://user-images.githubusercontent.com/3220162/63300970-52189c80-c28e-11e9-8062-85c51abb298a.gif)

Is this still an issue for you?

**Comment by mjangda** [comment] 2019-10-31 03:02
I've tested this with WordPress 5.3 RC2 as well and cannot reproduce either.

I'm going to close this issue but @beceha if you can still reproduce, please re-open with more details and we can take a look. Thanks!

**Closed by mjangda** 2019-10-31 03:02 UTC
