### ISSUE TITLE
Space missing in the post status UI

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#237] opened 2014-01-06 22:12 UTC
![image](https://f.cloud.github.com/assets/36432/1854655/a979011a-771f-11e3-85a7-bedaa086746a.png)

Label needs a space after it or similar.

**Comment by justnorris** [comment] 2018-01-18 15:36
Is this still a thing in WP 4.9.2 ?
![screen shot 2018-01-18 at 17 34 28](https://user-images.githubusercontent.com/988095/35106061-ed5c50b4-fc75-11e7-8edc-928d1bc2d810.png)

I tested in Firefox 58 and Chrome 63 and I can't reproduce the problem.

**Comment by WPprodigy** [comment] 2020-01-16 01:46
Hmm, I'm also unable to replicate. Tested chrome, safari, and firefox. Closing for now given the large time span.

**Closed by WPprodigy** 2020-01-16 01:46 UTC
Labels: Module: Custom Statuses, [Priority] Low, [Status] Needs Reporter Feedback, bug
